### ISSUE TITLE
Comando npm i @material-ui/core não funciona

### ISSUE THREAD

**Issue by Bruna0701** [Tautorn/covid19-dio#21]
Olá, professor.
Estava seguindo o passo a passo para criar o projeto, mas quando insiro o comando i @material-ui/core, ele retorna esse erro:
_______________________________________________________________________________________________________________
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: covid19-dio@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\bls19\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bls19\AppData\Local\npm-cache\_logs\2022-05-30T15_42_49_142Z-debug-0.log
_______________________________________________________________________________________________________________

Não sei como resolver e já até tentei recomeçar o projeto.
Desde já, agradeço a atenção.

**Comment by Tautorn** [comment]
@Bruna0701 o problema era a versão do `react-scripts`. Realizei a atualização do projeto. Está na master.
