### ISSUE TITLE
API Pública indisponível

### ISSUE THREAD

**Issue by tbathat** [Tautorn/covid19-dio#28]
Se verificarem, a url https://coronavirus-19-api.herokuapp.com/countries está inválida.

Gostaria de saber se alguém ou o @Tautorn teria uma sugestão de outra api pública semelhante.

**Comment by Tautorn** [comment]
Olá @tbathat , obrigado pelo retorno.

Estou verificando o ambiente.

**Comment by Tautorn** [comment]
@tbathat você pode estar utilizando essa api aqui: `https://covid-19-statistics.p.rapidapi.com/reports`
Mas pela `rapidapi.com` você precisa gerar a própria chave.

De todo jeito estou subindo em outro servidor um endpoint para atualizar o projeto.

**Comment by Tautorn** [comment]
CURL:

```
curl --location --request GET 'https://covid-19-statistics.p.rapidapi.com/reports' \
--header 'X-RapidAPI-Key: API_KEY' \
--header 'X-RapidAPI-Host: covid-19-statistics.p.rapidapi.com' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'region_name=BRAZIL'
```

**Comment by tbathat** [comment]
Maravilha @Tautorn! Muito obrigada. Eu não conhecia a API Hub, achei muito maneiro. Valeu a anteção! Sucesso.
